##### init.mac
#
## Set some default verbose
#
#/control/verbose 2
#/control/saveHistory
#/run/verbose 2
#
#/event/verbose 0
#/tracking/verbose 0
#
#/process/setVerbose 1 MuZeroDiffusion
#/process/setVerbose 1 MuZeroIonization
#/tracking/verbose 1
#
# Change the default number of threads (in multi-threaded mode)
#/run/numberOfThreads 4
#
# Initialize kernel - this is in setup.mac
#/run/initialize

# Visualization setting called independently
#/control/execute vis.mac
